#!/bin/tcsh

set epi="/mnt/c/Trabajo/Academia/Docencia/Cursos/2025/Curso_Redes2025/data/teaching_rsfmri_egv/data_00_basic/sub-112/ses-01/func/"
set SUMA="/mnt/c/Trabajo/Academia/Docencia/Cursos/2025/Curso_Redes2025/data/teaching_rsfmri_egv/derivatives/freesurfer/sub-112/SUMA"
set warp="/mnt/c/Trabajo/Academia/Docencia/Cursos/2025/Curso_Redes2025/data/teaching_rsfmri_egv/derivatives/freesurfer/sub-112/SUMA/o.aw_sub-112"

afni_proc.py                                                         \
    -subj_id                  sub-112.rest                             \
    -blocks                   despike tshift align tlrc volreg blur  \
                              mask scale regress                     \
    -radial_correlate_blocks  tcat volreg regress                    \
    -copy_anat                $warp/anatSS.sub-112.nii                          \
    -anat_has_skull           no                                     \
    -anat_follower            anat_w_skull anat $warp/anatU.sub-112.nii         \
    -anat_follower_ROI        aaseg anat                             \
                              $SUMA/aparc.a2009s+aseg_REN_all.nii.gz       \
    -anat_follower_ROI        aeseg epi                              \
                              $SUMA/aparc.a2009s+aseg_REN_all.nii.gz       \
    -anat_follower_ROI        FSvent epi $SUMA/fs_ap_latvent.nii.gz        \
    -anat_follower_ROI        FSWe epi $SUMA/fs_ap_wm.nii.gz               \
    -anat_follower_erode      FSvent FSWe                            \
    -dsets                    $epi/sub-112_ses-01_task-rest_run-01_bold.nii.gz                    \
    -tcat_remove_first_trs    2                                      \
    -align_unifize_epi        local                                  \
    -align_opts_aea           -cost lpc+ZZ                           \
                              -giant_move                            \
                              -check_flip                            \
    -tlrc_base                MNI152_2009_template_SSW.nii.gz        \
    -tlrc_NL_warp                                                    \
    -tlrc_NL_warped_dsets     $warp/anatQQ.sub-112.nii $warp/anatQQ.sub-112.aff12.1D       \
                              $warp/anatQQ.sub-112_WARP.nii                     \
    -volreg_align_to          MIN_OUTLIER                            \
    -volreg_align_e2a                                                \
    -volreg_tlrc_warp                                                \
    -mask_epi_anat            yes                                    \
    -blur_size                4                                      \
    -regress_apply_mot_types  demean deriv                           \
    -regress_motion_per_run                                          \
    -regress_anaticor_fast                                           \
    -regress_anaticor_label   FSWe                                   \
    -regress_ROI_PC           FSvent 3                               \
    -regress_ROI_PC_per_run   FSvent                                 \
    -regress_censor_motion    0.2                                    \
    -regress_censor_outliers  0.05                                   \
    -regress_make_corr_vols   aeseg FSvent                           \
    -regress_est_blur_epits                                          \
    -regress_est_blur_errts                                          \
    -html_review_style        pythonic
